title: Stud.IP -  Opencast Matterhorn Plugin
description: A Stud.IP Plugin for the OpenCast Matterhorn Project
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
